baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Raluca."
    subtitle: "I build things for web."
    content: "An enthusiastic back-end developer. I enjoy coding, problem solving, reading and learning foreign languages."
    image: /images/fea3d173a9fc454e032b6071bf7b473d.jpg
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://www.canva.com/design/DAFa8CZB3gQ/AN1NfzNg0GX3zS_ywqpFmg/view?utm_content=DAFa8CZB3gQ&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/KimKalura
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/floriana-raluca-deftu/
        - icon: fab fa-discord
          url: https://discord.gg/#7264
      customIcons:
        - icon: /fav.png
          url: "https://kimkalura.github.io/"

    # About
    about:
      enable: true
      title: "About Me"
      image: "/images/projects/programmer.jpg"
      content: |-
        My background is related to the humanities side, more precisely to translations.
        I have a passion for web development and curiosity laid me to this 'coding world'. I am open for any opportunity to be a back-end programmer developer, with different technologies.

        I am currently developing an application for learning and practicing a foreign language. The purpose is an educational one, of online cultural exchange, where polyglots and lovers of fiction and writing short prose/poetry will be able to interact.
      skills:
        enable: true
        title: "Here are a few technologies I've been working with recently:"
        items:
          - "Java"
          - "Spring Boot"
          - "OOP"
          - "MySQL"
          - "HTML"
          - "CSS"

    # Experience
    experience:
      enable: true
      # title: "Custom Name"
      items:
        - job: "Freelancer translator"
          date: "2021 - present"
          content: "I am currently working in translation domain. Source language - German, target language - Romanian. Field of specialization: Literature, History, Official documents"

    # Education
    education:
      enable: true
      # title: "Custom Name"
      index: false
      items:
        - title: "Back-end development"
          school:
            name: "JustCodeIt"
            url: "https://credsverse.com/credentials/b004ecb1-21a9-4c63-b688-925cac287c16"
          date: "2022 - 2023"
          content: |-
            Skills: Unit Testing · Back-end development · Java · Algorithms · OOP · Relational Databases · SQL · Git · HTML · CSS · Web services · REST APIs · Spring Boot · Spring Framework · MySQL · Data Structures · Web Development · Software Development
        - title: "Master's degree of German Culture in European Context"
          school:
            name: "Alexandru Ioan Cuza University"
            url: "https://www.uaic.ro/"
          date: "2018 - 2020"
          content: |-
            German Language and Literature

            Master's dissertation: Wanderschaft als jüdisches Motiv bei Joseph Roth

            Supplementary courses:
              - Chinese language
              - Korean language
              - Italian language
        - title: "Summer School"
          school:
            name: "Jagiellonian University"
            url: "https://isad.uj.edu.pl/en_GB/start"
          date: "2018 - 2018"
          content: |-
            - Polish Language and History
        - title: "Bachelor's degree of Language and Literature"
          school:
            name: "Alexandru Ioan Cuza University"
            url: "https://www.uaic.ro/"
          date: "2015 - 2018"
          content: |-
            Romanian Language and Literature - German Language and Literature

            Bachelor's thesis: Das Motiv der Schuld im Werk von Franz Kafka und Albert Camus

            Supplementary courses:
              - Chinese language
              - Hebrew language
              - Russian language
              - Modern Greek language
        - title: "High School"
          school:
            name: "Barbu Stirbei National College"
            url: "http://cnbs.ro/"


    #  # Achievements
    #  achievements:
    #    enable: true
    #    # title: "Custom Name"
    #    items:
    #      - title: Google kickstart runner
    #        content: I solved all problems with optimal solution.
    #        url: https://example.com
    #      - title: Facebook Hackathon Winner
    #        content: Developed a product using Artificial Intelligence.
    #      - title: Hugo Profile
    #        content: Developed a theme and getting 1K+ downloads per month.
    #        url: "https://github.com/gurusabarish/hugo-profile"
    #      - title: Microsoft Imagine Runner
    #        content: We are developed a product which can help others.
    #      - title: Google Summer of Code
    #        content: Contributed to a open source project.
    #        url: https://example.com

    # projects
    projects:
      enable: true
      # title: "Custom Name"
      items:
        - title: Language App
          content: An application for polyglots and lovers of literature. שפה חדשה היא חיים חדשים
          image: /images/projects/languages.jpg
          featured:
            name: Demo
            link: https://safe-wildwood-25661.herokuapp.com/swagger-ui/
          badges:
            - "Java"
            - "MySQL"
            - "Spring"
          links:
            - icon: fa fa-envelope
              url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
            - icon: fab fa-github
              url: https://github.com/KimKalura/Language-App-Final-Project

        - title: E-commerce
          content: A web application created for transactions made on the Internet.
          image: /images/projects/onlineshopping.png
          badges:
            - "Java"
            - "MySQL"
            - "Spring"
          links:
            - icon: fab fa-github
              url: https://github.com/KimKalura/Ecommerce

        - title: Cinema City
          content: Your favorite movie at a click away. An application designed for purchase cinema tickets.
          image: /images/projects/cinema.jpg
          badges:
            - "Java"
            - "MySQL"
            - "Spring"
          links:
            - icon: fab fa-github
              url: https://github.com/KimKalura/Cinema-City

        - title: Price Generator
          content: Price generator calculate discount for products and also can create a quote.
          image: /images/projects/price.png
          badges:
            - "Java"
            - "MySQL"
            - "Spring"
          links:
            - icon: fab fa-github
              url: https://github.com/KimKalura/Price-Generator

        - title: Hotel Reservation System
          content: This application allows the guest to be informed about the tariff of room reserved at time of booking and maintains records of the hotel occupancy.
          image: /images/projects/hotel.jpg
          badges:
            - "Java"
            - "MySQL"
            - "Spring"
          links:
            - icon: fab fa-github
              url: https://github.com/KimKalura/Booking

        - title: Code Sharing Platform
          content: This platform is dedicated to programmers who can share pieces of code but which cannot be made public.
          image: /images/projects/codesharing.jpg
          badges:
            - "Javaa"
            - "MySQL"
            - "Spring"
          links:
            - icon: fab fa-github
              url: https://github.com/KimKalura/Code-Sharing-Platform

        - title: Weather App
          content: This application display the latest official weather forecasts of a city.
          image: /images/projects/weather.jpg
          badges:
            - "Java"
            - "MySQL"
            - "Spring"
          links:
            - icon: fab fa-github
              url: https://github.com/KimKalura/Weather-App

        - title: Library Project
          content: It offers users and administrators functionality to borrow and return books.
          image: /images/projects/library.jpg
          badges:
            - "Java"
            - "MySQL"
            - "Spring"
          links:
            - icon: fab fa-github
              url: https://github.com/KimKalura/Library-Project


  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: raluca.deftu@yahoo.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "raluca.deftu@yahoo.com"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
